server:
    servlet:
        context-path: /rc-module
    error:
        include-message: always
    port: 8081
spring:
    application:
        name: 'rc-module'
    datasource:
        driver-class-name: com.ibm.db2.jcc.DB2Driver
        password: Bedis@Dsid001
        url: jdbc:db2://10.2.3.63:50000/DB2WLOC
        username: BEDIS001
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                default_schema: G2010R
        show-sql: false
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://13.38.124.17:8090/auth/realms/gainde
    zipkin:
        baseUrl: '#<url du zipkin>'
        enabled: false
        service:
            name: rc-module
        jdbc:
            datasource-proxy:
                query:
                    enable-logging: true
    sleuth:
        sampler:
            probability: '1'
        jdbc:
            datasource-proxy:
                slow-query:
                    enable-logging: true
                    log-level: WARN
                    logger-name: 'slow-query'
                    threshold: 10
spring-security-uri: http://13.38.124.17:8090/auth/realms/gainde/protocol/openid-connect/token

log4j:
    appender:
        file:
            layout:
                nodeValue: org.apache.log4j.PatternLayout
                ConversionPattern: '%d{HH:mm:ss,SSS} %-5p [%c] - %m%n'
            File:

logging:
    file:
        name: ${catalina.base:.}/logs/rc-module.log
    logback:
        rollingpolicy:
            clean-history-on-start: false
            file-name-pattern: '${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz'
            max-history: 100
            max-file-size: 10MB
    level:
        root: "info"
        org.springframework.web: "error"
        org.hibernate: "error"
